# Generated by Django 4.1.3 on 2022-12-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classNo', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseNo', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=32)),
                ('grade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('studentNo', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('photo', models.ImageField(default='user1.jpg', upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('teacherNo', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QianDaoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
        migrations.CreateModel(
            name='QianDao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qianDaoName', models.CharField(max_length=32)),
                ('courseName', models.CharField(max_length=32)),
                ('class1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.class')),
                ('pubtime', models.DateTimeField(auto_now_add=True)),
                ('duetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='app1.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.teacher'),
        ),
    ]
