# Generated by Django 2.2.2 on 2022-12-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mypicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('photo', models.ImageField(default='user1.jpg', upload_to='photos')),
            ],
        ),
    ]
