# Generated by Django 2.2.2 on 2023-01-05 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminNo', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('authNo', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='qiandao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qiandaomessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Tea_Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Authority')),
                ('teacherNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Stu_Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Authority')),
                ('studentNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Student')),
            ],
        ),
    ]
