# Generated by Django 4.1.3 on 2023-01-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_student_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="img_name",
            field=models.CharField(default=12345, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="qiandao",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="qiandaomessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stu_auth",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tea_auth",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
