# Generated by Django 4.1.3 on 2023-01-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_student_img_name_alter_qiandao_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="img_name",
            field=models.CharField(max_length=100),
        ),
    ]
