# Generated by Django 4.1.3 on 2023-01-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_alter_student_img_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(default="user1.jpg", upload_to="photos")),
            ],
        ),
    ]
