# Generated by Django 2.2.2 on 2023-01-09 06:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_studentphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='QianDao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qianDaoName', models.CharField(max_length=32)),
                ('courseName', models.CharField(max_length=32)),
                ('class1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.class')),
                ('pubtime', models.DateTimeField(auto_now_add=True)),
                ('duetime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='stu_auth',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentphoto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tea_auth',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StuQianDao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QianDaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.QianDao')),
                ('studentNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Student')),
            ],
        ),
    ]
