# Generated by Django 4.1.3 on 2023-01-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_teacher_password_stuqiandao_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_auth',
            name='authName',
            field=models.CharField(default='null', max_length=32),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
