# Generated by Django 4.1.3 on 2023-01-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_teacher_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='null', max_length=32),
        ),
    ]
