# Generated by Django 4.1.3 on 2023-01-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_teacher_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='password',
            new_name='password1',
        ),
    ]
